MODEL:
  BACKBONE:
    #CONV_BODY: "RESNET-18"
    CONV_BODY: "DD3D"
    USE_NORMALIZATION: "BN"
    DOWN_RATIO: 8
    BACKBONE_OUT_CHANNELS: 256
  SMOKE_HEAD:
    DIMENSION_REFERENCE: ((4.392, 1.658, 1.910),
                          (1.773, 1.525, 0.740),
                          (0.505, 1.644, 0.582),
                          (7.085, 2.652, 2.523),
                          (2.790, 1.651, 1.201),
                          (8.208, 2.869, 2.645))
    REGRESSION_HEADS: 9
    # Specific channel for (depth_offset, keypoint_offset, dimension_offset, orientation)
    REGRESSION_CHANNEL: (2, 2, 3, 2)
    REGRESSION_MULTI_HEADS: False
    LOSS_WEIGHT: (1., 2.)

    NORMALIZED_FOCAL_REFERENCE: 707.0
    LOSS_TYPE: ("GeneralizedFocalLoss", "DisL1")
    GENERALIZED_FL_BELTA: 2
    CLS_REWEIGHT_SHOT_GAMMA: 0.5
    CLS_REWEIGHT_SIZE_GAMMA: 0.0

FE:
  FPN:
    IN_FEATURES: [level3,level4,level5]
    # By default ('None'), returns all features.
    OUT_FEATURES: 
    OUT_CHANNELS: 256
    NORM: FrozenBN
    # Types for fusing the FPN top-down and lateral features. Can be either "sum" or "avg"
    FUSE_TYPE: sum
  BUILDER: build_fcos_dla_fpn_backbone_p67
  BACKBONE:
    NAME: DLA-34
    OUT_FEATURES: [level3,level4,level5]
    NORM: FrozenBN
  OUT_FEATURES: 

INPUT:
  HEATMAP_METHORD: "round"
  RADIUS_IOU: 0.5
  SHIFT_SCALE_PROB_TRAIN: 1.0
  SHIFT_SCALE_TRAIN: (0.2, 0.3)
  FLIP_PROB_TRAIN: 0.5

  HEIGHT_TRAIN: 512
  WIDTH_TRAIN: 768
  HEIGHT_TEST: 512
  WIDTH_TEST: 768

DATASETS:
  DETECT_CLASSES: ["Car", "Cyclist", "Pedestrian", "Truck", "Tricycle", "Bus"]
  TRAIN: ["waymo720front_train"]
  TEST: ["waymo720front_val"]
  MAX_OBJECTS: 1000
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  OPTIMIZER: "Adam"
  SCHEDULER: "WarmupMultiStepLR"
  #SCHEDULER: "MultiStepLR"
  BASE_LR: 16e-4
  STEPS: [20000,40000,60000,80000]
  #STEPS: [10000,25000]
  DESCENT_RATE: 0.5
  #MAX_ITERATION: 100000
  MAX_ITERATION: 100000
  WARMUP_ITERS: 10000
  #WARMUP_ITERS: 5000
  WARMUP_FACTOR: 0.25
  IMS_PER_BATCH: 5
  EVALUATE_STEP_PERIOD: 1000
  #EVALUATE_STEP_PERIOD: 100

  PRETRAIN_MODEL: ""
  EXCLUDE_LAYERS: []
  RESUME: False
TEST:
  DETECTIONS_THRESHOLD: 0.25
  DEPTH_RANGES: [[0,30],[0,15],[15,30]]
  IOU_THRESHOLDS: [0.7, 0.25, 0.25, 0.7, 0.25, 0.7]

OUTPUT_DIR: "./checkpoint/multi_head"