MODEL:
  BACKBONE:
    CONV_BODY: "RESNET-18"
    USE_NORMALIZATION: "BN"
    DOWN_RATIO: 4
    BACKBONE_OUT_CHANNELS: 64
  SMOKE_HEAD:
    NORMALIZED_FOCAL_REFERENCE: -1.0
INPUT:
  HEIGHT_TRAIN: 384
  WIDTH_TRAIN: 1280
  HEIGHT_TEST: 384
  WIDTH_TEST: 1280
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
  TEST_AFFINE_TRANSFORM: True
DATASETS:
  DETECT_CLASSES: ["Car", "Cyclist", "Pedestrian"]
  TRAIN: ["kitti_train"]
  TEST: ["kitti_val"]
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  OPTIMIZER: "Adam"
  SCHEDULER: "MultiStepLR"
  BASE_LR: 5e-4
  STEPS: [10000, 25000, 35000]
  MAX_ITERATION: 50000
  IMS_PER_BATCH: 32
  EVALUATE_STEP_PERIOD: 2000
TEST:
  DETECTIONS_THRESHOLD: 0.25
  DEPTH_RANGES: [[0,30],[30,60],[0,15],[15,30],[0,60]]
  IOU_THRESHOLDS: [0.7, 0.25, 0.25, 0.7, 0.25, 0.7]

OUTPUT_DIR: "./checkpoint/kitti_resnet18_batch32/"
